version: '3.9'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_HOST=mongo
      - PORT=3000
