version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo:/data/db
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_HOST=mongo
      - PORT=3000

volumes:
  mongo: {}
